name: proxy-custodian
base: core24
version: "0.1"
summary: The custodian of the proxy registry.
description: |
  The custodian of the proxy registry.
grade: devel
confinement: strict

plugs:
  proxy-control:
    interface: registry
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: proxy/control-proxy
    role: custodian

parts:
  proxy-custodian:
    plugin: dump
    source: .

apps:
  sh:
    command: /bin/sh
    plugs:
      - proxy-control
