name: browser
base: core24
version: "0.1"
summary: Snap that consumes proxy config.
description: |
  Snap that consumes proxy config.
grade: devel
confinement: strict

plugs:
  proxy-observe:
    interface: registry
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: proxy/observe-proxy

parts:
  browser:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-packages:
      - requests==2.32.3
      - html2text==2024.2.26
      - connect-markdown-renderer==3.0.0

apps:
  browser:
    command: /bin/browser-cli
    plugs:
      - network
      - proxy-observe
