name: net-ctrl
base: core24
version: "0.1"
summary: The custodian of the network registry.
description: |
  The custodian of the network registry.
grade: devel
confinement: strict

plugs:
  proxy-control:
    interface: registry
    account: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN
    view: network/control-proxy
    role: custodian

parts:
  net-ctrl:
    plugin: dump
    source: .

apps:
  sh:
    command: /bin/sh
    plugs:
      - proxy-control
