name: net-ctrl
base: core24
version: "0.1"
summary: The custodian of the network confdb.
description: |
  The custodian of the network confdb.
grade: devel
confinement: strict

plugs:
  proxy-control:
    interface: confdb
    account: 6mluykWFsbpSV8RGPGjH7KFAkAOvdRyN
    view: network/control-proxy
    role: custodian

parts:
  net-ctrl:
    plugin: python
    source: .
    python-packages:
      - validators==0.34.0
    override-prime: |
      snapcraftctl prime
      mkdir -p ${SNAPCRAFT_PRIME}/bin
      cp ${SNAPCRAFT_PART_SRC}/bin/sh ${SNAPCRAFT_PRIME}/bin

apps:
  sh:
    command: /bin/sh
    plugs:
      - proxy-control
